# Generated by Django 3.2.5 on 2021-07-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('dni', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('monto', models.FloatField(max_length=1000)),
                ('aprobado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(max_length=1000)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditos.clientes')),
            ],
        ),
    ]
