# Generated by Django 3.2.5 on 2021-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos',
            name='aprobado',
            field=models.BooleanField(default='null'),
        ),
    ]
